"""create master data schema

Revision ID: 44f5a70a766a
Revises: 27d6bd3c881a
Create Date: 2026-09-18 16:37:52.713638

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '44f5a70a766a'
down_revision: Union[str, Sequence[str], None] = '27d6bd3c881a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('school_code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_code', name='uq_schools_school_code')
    )
    op.create_table('colleges',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.Column('college_code', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name='fk_colleges_school_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'school_id', name='uq_colleges_id_school_id')
    )
    op.create_index(op.f('ix_colleges_school_id'), 'colleges', ['school_id'], unique=False)
    op.create_index('uq_colleges_school_college_code', 'colleges', ['school_id', 'college_code'], unique=True, postgresql_where=sa.text('college_code IS NOT NULL'))
    op.create_table('exam_subjects',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('school_id', sa.BigInteger(), nullable=True),
    sa.Column('subject_code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name='fk_exam_subjects_school_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_subjects_school_id'), 'exam_subjects', ['school_id'], unique=False)
    op.create_index('uq_exam_subjects_national_code', 'exam_subjects', ['subject_code'], unique=True, postgresql_where=sa.text('school_id IS NULL'))
    op.create_index('uq_exam_subjects_school_code', 'exam_subjects', ['school_id', 'subject_code'], unique=True, postgresql_where=sa.text('school_id IS NOT NULL'))
    op.create_table('majors',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.Column('major_code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('degree_type', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("degree_type IN ('academic', 'professional')", name='ck_majors_degree_type'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name='fk_majors_school_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'school_id', name='uq_majors_id_school_id'),
    sa.UniqueConstraint('school_id', 'major_code', name='uq_majors_school_major_code')
    )
    op.create_table('admission_catalogs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.Column('college_id', sa.BigInteger(), nullable=False),
    sa.Column('major_id', sa.BigInteger(), nullable=False),
    sa.Column('admission_year', sa.SmallInteger(), nullable=False),
    sa.Column('study_mode', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("study_mode IN ('full_time', 'part_time')", name='ck_admission_catalogs_study_mode'),
    sa.CheckConstraint('admission_year >= 2000', name='ck_admission_catalogs_year'),
    sa.ForeignKeyConstraint(['college_id', 'school_id'], ['colleges.id', 'colleges.school_id'], name='fk_admission_catalogs_college_school', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['major_id', 'school_id'], ['majors.id', 'majors.school_id'], name='fk_admission_catalogs_major_school', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name='fk_admission_catalogs_school_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'college_id', 'major_id', 'admission_year', 'study_mode', name='uq_admission_catalogs_offering')
    )
    op.create_index(op.f('ix_admission_catalogs_college_id'), 'admission_catalogs', ['college_id'], unique=False)
    op.create_index(op.f('ix_admission_catalogs_major_id'), 'admission_catalogs', ['major_id'], unique=False)
    op.create_index('ix_admission_catalogs_school_year', 'admission_catalogs', ['school_id', 'admission_year'], unique=False)
    op.create_index('ix_admission_catalogs_year', 'admission_catalogs', ['admission_year'], unique=False)
    op.create_table('admission_catalog_directions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('admission_catalog_id', sa.BigInteger(), nullable=False),
    sa.Column('direction_code', sa.String(length=32), nullable=False),
    sa.Column('direction_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admission_catalog_id'], ['admission_catalogs.id'], name='fk_admission_catalog_directions_catalog_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admission_catalog_id', 'direction_code', name='uq_admission_catalog_directions_code')
    )
    op.create_table('admission_catalog_exam_subjects',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('admission_catalog_id', sa.BigInteger(), nullable=False),
    sa.Column('exam_subject_id', sa.BigInteger(), nullable=False),
    sa.Column('exam_unit', sa.SmallInteger(), nullable=False),
    sa.Column('option_order', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('exam_unit BETWEEN 1 AND 4', name='ck_catalog_exam_unit'),
    sa.CheckConstraint('option_order >= 1', name='ck_catalog_exam_option_order'),
    sa.ForeignKeyConstraint(['admission_catalog_id'], ['admission_catalogs.id'], name='fk_admission_catalog_exam_subjects_catalog_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['exam_subject_id'], ['exam_subjects.id'], name='fk_admission_catalog_exam_subjects_subject_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admission_catalog_id', 'exam_unit', 'exam_subject_id', name='uq_catalog_exam_unit_subject'),
    sa.UniqueConstraint('admission_catalog_id', 'exam_unit', 'option_order', name='uq_catalog_exam_unit_option_order')
    )
    op.create_index(op.f('ix_admission_catalog_exam_subjects_exam_subject_id'), 'admission_catalog_exam_subjects', ['exam_subject_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admission_catalog_exam_subjects_exam_subject_id'), table_name='admission_catalog_exam_subjects')
    op.drop_table('admission_catalog_exam_subjects')
    op.drop_table('admission_catalog_directions')
    op.drop_index('ix_admission_catalogs_year', table_name='admission_catalogs')
    op.drop_index('ix_admission_catalogs_school_year', table_name='admission_catalogs')
    op.drop_index(op.f('ix_admission_catalogs_major_id'), table_name='admission_catalogs')
    op.drop_index(op.f('ix_admission_catalogs_college_id'), table_name='admission_catalogs')
    op.drop_table('admission_catalogs')
    op.drop_table('majors')
    op.drop_index('uq_exam_subjects_school_code', table_name='exam_subjects', postgresql_where=sa.text('school_id IS NOT NULL'))
    op.drop_index('uq_exam_subjects_national_code', table_name='exam_subjects', postgresql_where=sa.text('school_id IS NULL'))
    op.drop_index(op.f('ix_exam_subjects_school_id'), table_name='exam_subjects')
    op.drop_table('exam_subjects')
    op.drop_index('uq_colleges_school_college_code', table_name='colleges', postgresql_where=sa.text('college_code IS NOT NULL'))
    op.drop_index(op.f('ix_colleges_school_id'), table_name='colleges')
    op.drop_table('colleges')
    op.drop_table('schools')
    # ### end Alembic commands ###
