"""create teacher data schema

Revision ID: 695107900fc3
Revises: 44f5a70a766a
Create Date: 2026-10-04 19:56:32.811717

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '695107900fc3'
down_revision: Union[str, Sequence[str], None] = '44f5a70a766a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_profiles',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('availability_status', sa.String(length=32), server_default=sa.text("'unknown'"), nullable=False),
    sa.Column('verification_status', sa.String(length=32), server_default=sa.text("'unverified'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("availability_status IN ('unknown', 'available', 'unavailable')", name='ck_teacher_profiles_availability'),
    sa.CheckConstraint("verification_status IN ('unverified', 'verified', 'rejected')", name='ck_teacher_profiles_verification'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher_teach_subjects',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('teacher_profile_id', sa.BigInteger(), nullable=False),
    sa.Column('exam_subject_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_subject_id'], ['exam_subjects.id'], name='fk_teacher_teach_subjects_exam_subject_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['teacher_profile_id'], ['teacher_profiles.id'], name='fk_teacher_teach_subjects_teacher_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_profile_id', 'exam_subject_id', name='uq_teacher_teach_subjects_teacher_subject')
    )
    op.create_index(op.f('ix_teacher_teach_subjects_exam_subject_id'), 'teacher_teach_subjects', ['exam_subject_id'], unique=False)
    op.create_table('admission_records',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('teacher_profile_id', sa.BigInteger(), nullable=False),
    sa.Column('school_id', sa.BigInteger(), nullable=False),
    sa.Column('college_id', sa.BigInteger(), nullable=False),
    sa.Column('major_id', sa.BigInteger(), nullable=False),
    sa.Column('admission_year', sa.SmallInteger(), nullable=False),
    sa.Column('study_mode', sa.String(length=32), nullable=False),
    sa.Column('admission_catalog_id', sa.BigInteger(), nullable=True),
    sa.Column('initial_total', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('retest_total', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('final_total', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("study_mode IN ('full_time', 'part_time')", name='ck_admission_records_study_mode'),
    sa.CheckConstraint('admission_year >= 2000', name='ck_admission_records_year'),
    sa.CheckConstraint('final_total IS NULL OR final_total >= 0', name='ck_admission_records_final_total_nonnegative'),
    sa.CheckConstraint('initial_total IS NULL OR initial_total >= 0', name='ck_admission_records_initial_total_nonnegative'),
    sa.CheckConstraint('retest_total IS NULL OR retest_total >= 0', name='ck_admission_records_retest_total_nonnegative'),
    sa.ForeignKeyConstraint(['admission_catalog_id'], ['admission_catalogs.id'], name='fk_admission_records_catalog_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['college_id', 'school_id'], ['colleges.id', 'colleges.school_id'], name='fk_admission_records_college_school', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['major_id', 'school_id'], ['majors.id', 'majors.school_id'], name='fk_admission_records_major_school', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name='fk_admission_records_school_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['teacher_profile_id'], ['teacher_profiles.id'], name='fk_admission_records_teacher_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_profile_id', 'school_id', 'college_id', 'major_id', 'admission_year', 'study_mode', name='uq_admission_records_teacher_offering')
    )
    op.create_index(op.f('ix_admission_records_admission_catalog_id'), 'admission_records', ['admission_catalog_id'], unique=False)
    op.create_index(op.f('ix_admission_records_college_id'), 'admission_records', ['college_id'], unique=False)
    op.create_index(op.f('ix_admission_records_major_id'), 'admission_records', ['major_id'], unique=False)
    op.create_index('ix_admission_records_school_year', 'admission_records', ['school_id', 'admission_year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_admission_records_school_year', table_name='admission_records')
    op.drop_index(op.f('ix_admission_records_major_id'), table_name='admission_records')
    op.drop_index(op.f('ix_admission_records_college_id'), table_name='admission_records')
    op.drop_index(op.f('ix_admission_records_admission_catalog_id'), table_name='admission_records')
    op.drop_table('admission_records')
    op.drop_index(op.f('ix_teacher_teach_subjects_exam_subject_id'), table_name='teacher_teach_subjects')
    op.drop_table('teacher_teach_subjects')
    op.drop_table('teacher_profiles')
    # ### end Alembic commands ###
